#!/bin/bash
if [ ! -n "$1" ]; then
echo au no scene name
exit 1
fi

SCENENAME="$1"
echo Make new scene "$1" in "../Scener/$SCENENAME"
pwd

mkdir -p "../Scener/${SCENENAME}"
cp -n ../Scener/_template/_template.core.maxpat "../Scener/${SCENENAME}/${SCENENAME}.core.maxpat"

#change the scene name argument for the SceneCore bpatcher
PATCHFILE="../Scener/${SCENENAME}/${SCENENAME}.maxpat"
if [ ! -f $PATCHFILE ]; then
SEDARGS='s/\"_template\"/\"'
SEDARGS=$SEDARGS${SCENENAME}
SEDARGS=$SEDARGS"\"/"
sed -e $SEDARGS <../Scener/_template/_template.maxpat >"../Scener/${SCENENAME}/${SCENENAME}.maxpat"
exit 0
else
echo "file already exists"
exit 127
fi
