#!/bin/bash
if [ ! -n "$1" ]; then
  echo au no scene path
  exit 1
fi

SCENEPATH="$1"
if [ ! -d $SCENEPATH ]; then
  SCENENAME="$(basename $SCENEPATH)"
  echo Make new scene in "$SCENEPATH"
  echo Scene name is "$SCENENAME"
  pwd

  mkdir -p "${SCENEPATH}"
  cp -n ../Scener/_template/_template.core.maxpat "${SCENEPATH}/${SCENENAME}.core.maxpat"

  #change the scene name argument for the SceneCore bpatcher
  PATCHFILE="${SCENEPATH}/${SCENENAME}.maxpat"
  SEDARGS='s/\"_template\"/\"'
  SEDARGS=$SEDARGS${SCENENAME}
  SEDARGS=$SEDARGS"\"/"
  sed -e $SEDARGS <../Scener/_template/_template.maxpat >"$PATCHFILE"
  exit 0
else
  echo "scene already exists"
  exit 127
fi
